### PR TITLE
interface in tests using one config file

### PR DESCRIPTION
**Pull request by koekie**
Due to issue #59 I had to change the password in all tests. This pull request moves the credentials to one config file which is used by pyxnat.Interface in the tests.

### CODE REVIEW

**Comment by bud42** [comment]
David, could you also update PyPI?
-Brian

**Comment by DavidJJ** [comment]
That requires me to remember how to do it.... please stand by.

**Comment by bud42** [comment]
There are actually instructions in the pyxnat README that github displays
on the repo homepage.

**Comment by DavidJJ** [comment]
pypi should be updated.  Issue created based on problems during build.

**Comment by bud42** [comment]
Looks good. Thanks!
-Brian

**Pull request merged**
