### PR TITLE
Adding cr and the event_reason to uri if cr set to TRUE

### PR DESCRIPTION
**Pull request by byvernault**
Hi Dave J. and Pyxnat Team,

First of all, thank you very much for all the work put into this package. We use it constantly. 

Second, I recently start using XNAT CR for one of our project and I realised that there is an issue with the Rest API Calls and XNAT CR. To create/upload resources or objects, you need to add an extra string to your API Calls. I worked on adding this into pyxnat as a variable cr for the interface.
It will add the string 'event_reason=RestAPIPyxnat' to any URI that are a POST or PUT or DELETE.

WDYT?

Let me know if you think I should change something.

Kind Regards,

Ben

### CODE REVIEW

**Comment by mmodat** [comment]
Hi all,

@DavidJJ Do you think someone would be able to have a look at this one? If something needs to be done on the code, please let us know.

Thanks,
Marc

**Comment by johnflavin** [comment]
This issue originally spawned from an xnat discussion board question. I posted a response over there (https://groups.google.com/d/msg/xnat_discussion/H0J5DZBBrOA/EelQMBbsAwAJ) but it is probably worth repeating it here.

> ...I suspect that if you add the argument `params={"event_reason": "Whatever"}` to your put/post/delete lines, that might solve your problem...

I could give more specific advice if I saw the lines of code that aren't working.

**Comment by bariskanber** [comment]
Hi John,
That makes sense, thank you. 

The only place where it may not work is perhaps when we do something like:
project.resource('NIFTI').file('T1.nii').insert('/tmp/image.nii')

Where an event_reason may also be required (but I am not sure).

Thanks for your help. We will modify our code and revert.

Cheers,
Baris.

**Comment by bariskanber** [comment]
Dear John,
I have made some investigating and found at least 2 cases where it seemed not possible to pass the event_reason parameter:

(1) When we do something like sess_obj.attrs.set('%s/original' % xsi_type,                             UPDATE_PREFIX + update_str)

(2) When we do something like: resource_obj.file(str(filename)).put(str(filepath), overwrite=True)
The latter produces something like (Debug output): ('PUT', u'/data/projects/GENFI_01/subjects/GENFI2_S00008/experiments/GENFI2_E00005/scans/1/resources/NIFTI') and any extra parameters passed are ignored (EObject::create function in resources.py).

Many thanks &
Kind regards,
Baris.

**Comment by johnflavin** [comment]
Baris, I think I may have fixed those two issues. I made PR #72 with my changes. If it is possible for you to build pyxnat from a branch, you could try those out and see if they work for you.

**Comment by bariskanber** [comment]
Hi John,
Thank you, that did help.
However, I had to put a temporary hack "query_args.update(datatypes['params'])" at line 1934 of resources.py (function File(EObject):put) in pyxnat/core just after these statements:

query_args = {
            'format': format,
            'content': content,
            'tags': tags,
            'overwrite': 'true' if overwrite else 'false',
            'inbody':'true'
            }

This was because although event_reason was being passed to the creation of the resource folder, it wasn't to the actual posting of the files.

This was a bit of a hack though, I am not sure how appropriate it is (you can perhaps replace it with a more appropriate statement/approach to achieve the same result).

Cheers,
Baris.

**Comment by johnflavin** [comment]
Yeah, I can see why you had to do that. I think that might be fine. You should probably add some checks to make sure that `datatypes` has a key `params` or else you'll get a `KeyError`. For instance, you could do
```python
if 'params' in datatypes:
    query_args.update(datatypes['params'])
```
or something like that.

The problem we're working around here is that the `datatypes` argument to that function looks to me like it is already a hack. It is using the `kwargs` pattern, but for a specific purpose that is known in advance; that indicates to me it should have been called out specifically in the method signature and should never have been a `kwargs` param to begin with. Now I want to use the `kwargs` to allow consumers of these methods pass in anything you want and it will go straight down to the underlying requests puts and posts. 

But in the interests of time and effort I want to be minimally invasive, so it seems fine to me to make the adjustment that you did.

**Comment by bariskanber** [comment]
Great, thanks John. I will touch base if we come across anything else.

**Comment by bariskanber** [comment]
Hi John,
I have completed testing the PyXNAT modifications for XNAT CR. Do you think we can pull these modifications to the mainstream PyXNAT?

I have created a pull request to NrgXnat/pyxnat -- I am not sure what the difference is compared to pyxnat/pyxnat. The former seems to be forked from the latter and my one was forked from the former.

Many thanks &
Kind regards,
Baris.

Mentioning:
@johnflavin 
@byvernault 
@mmodat

**Comment by bariskanber** [comment]
Hi John,
Sorry to trouble you again. Just wondering if you have had a chance to consider the above?
Many thanks,
Baris.

**Comment by johnflavin** [comment]
Ah, yes, sorry. I had forgotten about this. I'll continue the conversation at nrgxnat/pyxnat#2.

**Pull request closed without merging**
