### PR TITLE
Basic support for XNAT Pipelines

### PR DESCRIPTION
**Pull request by jhuguetn**
This PR includes basic functionalities for running and monitoring XNAT pipelines. 
Some CI tests for the added methods are also included to keep the coverage ratio.

### CODE REVIEW

**Comment by jhuguetn** [comment]
PR branch rebased

**Comment by jhuguetn** [comment]
PR branch rebased (again)

**Comment by jhuguetn** [comment]
PR rebased and ready to merge @xgrg

**Comment by xgrg** [comment]
Thank you @jhuguetn. We already have discussed most of it offline.
One last question though: can you briefly comment on why the `add` function was removed?

**Comment by jhuguetn** [comment]
Few reasons,
- Function is currently not working nor under Unit Testing control.
- Functionality is not listed as a supported one in the XNAT API directory (see [Project Pipeline Management API](https://wiki.xnat.org/display/XAPI/Project+Pipeline+Management+API)).
- Generally speaking I don't like adding administrative features to `pyxnat`. 
- This PR focuses on adding support to *basic* Pipeline functionalities.
- Note that `add()` code content is left commented for future work (if that could apply).

**Comment by xgrg** [comment]
Got it, thanks. That was worth asking the question.

**Pull request merged**
