### PR TITLE
FreeSurfer 7.2 additional segmentation results

### PR DESCRIPTION
**Pull request by jhuguetn**
New `freesurfer7_extras` derivative to make pyxnat compatible with results generated (via pipeline) by the following FreeSurfer 7.2 additional segmentation modules,
* Thalamic Nuclei segmentation [module](https://freesurfer.net/fswiki/ThalamicNuclei)
* Brainstem Substructures segmentation [module](https://freesurfer.net/fswiki/BrainstemSubstructures)
* Hypothalamic Subunits segmentation [module](https://freesurfer.net/fswiki/HypothalamicSubunits)

### CODE REVIEW

**Comment by xgrg** [comment]
For the record we have discussed this PR offline.

**Comment by xgrg** [comment]
Is there a way to fix the coverage rate alert? The rest looks alright to me.

**Comment by jhuguetn** [comment]
The subtle drop in coverage % in my `pyxnat` fork is not derived from the changes introduced by the PR. Is a consequence of running `sessionmirror.py` simultaneously for several Python versions (see Travis-CI [config](https://github.com/pyxnat/pyxnat/blob/bbrc/.travis.yml)) over the same data entities.  

For pure randomness, [one](https://coveralls.io/jobs/85233737) of the CI jobs from the last [build](https://coveralls.io/builds/42102235) found a empty resource while running `sessionmirror.py` test (probably being deleted/created at the very same moment by another CI job) and that covered 2 additional [lines](https://coveralls.io/builds/42102235/source?filename=bin%2Fsessionmirror.py#L519) of code of the `sessionmirror.py` script, thus increasing the overall coverage ratio.  
This eventuality however was not repeated during the last commit/[build](https://coveralls.io/builds/42703049), resulting in a warning/alert for the _faux_ decrease of the coverage. 

(PS: Ignore it)

**Comment by xgrg** [comment]
Thank you @jhuguetn for clarifying this. Merging now.

**Pull request merged**
