### PR TITLE
remove obsolete dependency on SIX

### PR DESCRIPTION
**Pull request by a-detiste**
https://wiki.debian.org/Python3-six-removal

@emollier

### CODE REVIEW

**Comment by a-detiste** [comment]
CI error is unrelated

**Comment by emollier** [comment]
Hi, as far as I can witness, the patch doesn't introduce any visible regressions in the current pyxnat 1.6 available in Debian sid; I have not tested the package thoroughly like an end user would though.

**Comment by a-detiste** [comment]
Debian is trying to remove usage of python3-future, which is also handled in this PR.

**Comment by jhuguetn** [comment]
Thanks @a-detiste and @emollier for your proposal, good catch(es)! I am very much in favor of getting rid of them as internal dependencies.  Could you perhaps open an issue referring to those deprecations mentioned (`six` and `future`) and backing up the proposal of removing those dependencies? 

CI error is indeed not related to the proposed changes in pyxnat code base. HTTP requests return an error #401 (unauthorized) when login to XNAT Central, seems like the sys-account used for testing has been disabled. I will further investigate this.

**Comment by a-detiste** [comment]
six & future were compatibility layers to help migrate from Python 2 in small steps.

 They now have outlived their purpose but would make you project look crusty and abandonned, which could scare away potential users/contributors.

**Comment by a-detiste** [comment]
"future" is breaking now with python3.12.

"six" might break later.

They are both unmaintained.

Their authors have moved away.

**Comment by a-detiste** [comment]
ping

**Comment by jhuguetn** [comment]
Hi @a-detiste, can you please rebase your PR branch onto master?

**Review by jhuguetn — COMMENTED** [review]
All good, checked against local fork and passes the CI tests. Let's merge

**Pull request merged**
