### PR TITLE
BASIL derivative

### PR DESCRIPTION
**Pull request by jhuguetn**
New `basil` derivative functionalities to make pyxnat compatible with results generated by FSL BASIL (`oxford_asl`), a toolbox for the analysis of perfusion ASL data.

### CODE REVIEW

**Comment by xgrg** [comment]
Looks good! A few comments:
- `_fix_label`: could we add some backing reference to support the claim that BASIL comes with typos? I also assume the function can be cut by half using a dictionary to fix those labels.
- `regional_stats`: I would shorten it to `stats()` for brevity and consistency with other modalities eg. `BAMOS` (and yeah, somewhat in advance, not a huge fan of `hypothalamic_subunits_volumes()` either 😅)
Thank you @jhuguetn!

**Comment by jhuguetn** [comment]
* `_fix_label`: I couldn't find any reference to such alleged typo issue so I've created one (https://github.com/physimals/oxford_asl/issues/22). Names such as `perfusion_wm_wm_mean.txt` or `perfusion_wm_calib_wm_mean.txt` were inconsistent with its GM counterparts thus I inferred that a typo error might be the cause.
Function was created to stress (make it clear for the maintainer) the existence of a typo in some filenames and how we got it fixed to use those names as `metric` labels. The code (simple if/else statement) is resilient to having filenames added/modified/fixed in further `oxford_asl` versions while a simple dictionary-based translation would perhaps be more rigid.

* `regional_stats`: Unlike `BAMOS`, name was inspired by the `oxford_asl` feature used to generate those ([region-analysis](https://asl-docs.readthedocs.io/en/latest/oxford_asl_userguide.html#region-analysis)). I see no problem in making it briefer though.

**Comment by jhuguetn** [comment]
Included a new `filepath` column in `basil.perfusion()` results table to preserve the provenance of the collected metrics once relabeled (46f2a91d121698917de551ba85e843d5eeaccf1a).

**Comment by xgrg** [comment]
Looks good to me. Merging.
Thank you @jhuguetn.

**Pull request merged**
